services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    environment:
      DATABASE_URL: ${DATABASE_URL}  
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped