services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    restart: unless-stopped