services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID} # Adicionado
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET} # Adicionado
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped